import type { HalloweenCategory } from './ghosts.js';

/**
 * Maps real-world Mapbox Standard POIs (by their `maki` icon id, from the basemap's `poi`
 * featureset) onto one of our 6 fictional Halloween categories, so tapping an ordinary POI (a
 * theatre, a shop, a church...) also summons a themed ghost — not just the 9 fictional POIs in
 * poi-data.ts. Covers the same ~124 maki ids as the vanilla example's full POI list (see
 * apps/studio/public/styles/sound-style-basic.json's poi-ping-* layers) so real-world clicks are
 * rarely a silent no-op, just grouped into our 6 ghost skins instead of one real-world sound each.
 * Kept in sync by hand with the real-POI `halloween-ping-<maki>` (or `halloween-ping-real-<maki>`
 * for the 2 maki values that collide with one of our own category names) sound-layers in
 * sound-style-halloween.json — see the suffix-resolution logic in src/main.ts.
 */
export const MAKI_TO_HALLOWEEN_CATEGORY: Record<string, HalloweenCategory> = {
  // -> cemetery (quiet outdoor/nature grounds)
  cemetery: 'cemetery',
  'dog-park': 'cemetery',
  campsite: 'cemetery',
  farm: 'cemetery',
  garden: 'cemetery',
  park: 'cemetery',
  'picnic-site': 'cemetery',
  waterfall: 'cemetery',
  'hot-spring': 'cemetery',
  beach: 'cemetery',
  watermill: 'cemetery',

  // -> haunted-mansion (grand/eerie attractions, adventure, recreation)
  castle: 'haunted-mansion',
  attraction: 'haunted-mansion',
  landmark: 'haunted-mansion',
  theatre: 'haunted-mansion',
  cinema: 'haunted-mansion',
  casino: 'haunted-mansion',
  'amusement-park': 'haunted-mansion',
  zoo: 'haunted-mansion',
  aquarium: 'haunted-mansion',
  heliport: 'haunted-mansion',
  racetrack: 'haunted-mansion',
  'racetrack-horse': 'haunted-mansion',
  windmill: 'haunted-mansion',
  'communications-tower': 'haunted-mansion',
  stadium: 'haunted-mansion',
  'american-football': 'haunted-mansion',
  baseball: 'haunted-mansion',
  basketball: 'haunted-mansion',
  'bowling-alley': 'haunted-mansion',
  golf: 'haunted-mansion',
  tennis: 'haunted-mansion',
  'table-tennis': 'haunted-mansion',
  volleyball: 'haunted-mansion',
  skateboard: 'haunted-mansion',
  'horse-riding': 'haunted-mansion',
  swimming: 'haunted-mansion',
  'fitness-centre': 'haunted-mansion',
  skiing: 'haunted-mansion',
  music: 'haunted-mansion',
  embassy: 'haunted-mansion',
  'town-hall': 'haunted-mansion',
  lodging: 'haunted-mansion',

  // -> monument (dignified/academic/geographic landmarks)
  monument: 'monument',
  museum: 'monument',
  'art-gallery': 'monument',
  library: 'monument',
  college: 'monument',
  school: 'monument',
  playground: 'monument',
  mountain: 'monument',
  'mountain-range': 'monument',
  peak: 'monument',
  pitch: 'monument',
  globe: 'monument',
  viewpoint: 'monument',
  doctor: 'monument',
  hospital: 'monument',
  slipway: 'monument',

  // -> witch-shop (commerce, food, vehicles/services)
  shop: 'witch-shop',
  bakery: 'witch-shop',
  bank: 'witch-shop',
  'clothing-store': 'witch-shop',
  confectionery: 'witch-shop',
  convenience: 'witch-shop',
  furniture: 'witch-shop',
  hardware: 'witch-shop',
  grocery: 'witch-shop',
  'jewelry-store': 'witch-shop',
  'mobile-phone': 'witch-shop',
  optician: 'witch-shop',
  pharmacy: 'witch-shop',
  post: 'witch-shop',
  shoe: 'witch-shop',
  suitcase: 'witch-shop',
  watch: 'witch-shop',
  bar: 'witch-shop',
  beer: 'witch-shop',
  'fast-food': 'witch-shop',
  cafe: 'witch-shop',
  restaurant: 'witch-shop',
  'restaurant-casual': 'witch-shop',
  'restaurant-noodle': 'witch-shop',
  'restaurant-pizza': 'witch-shop',
  'restaurant-seafood': 'witch-shop',
  'restaurant-sushi': 'witch-shop',
  'ice-cream': 'witch-shop',
  'alcohol-shop': 'witch-shop',
  car: 'witch-shop',
  'car-rental': 'witch-shop',
  'car-repair': 'witch-shop',
  'car-wash': 'witch-shop',
  fuel: 'witch-shop',
  taxi: 'witch-shop',
  toll: 'witch-shop',
  tunnel: 'witch-shop',
  bridge: 'witch-shop',
  'highway-rest-area': 'witch-shop',
  'highway-services': 'witch-shop',
  parking: 'witch-shop',
  'parking-garage': 'witch-shop',
  'parking-paid': 'witch-shop',
  'charging-station': 'witch-shop',
  bicycle: 'witch-shop',
  laundry: 'witch-shop',
  industry: 'witch-shop',

  // -> church (worship)
  'place-of-worship': 'church',
  'religious-christian': 'church',
  'religious-buddhist': 'church',
  'religious-jewish': 'church',
  'religious-muslim': 'church',
  'religious-shinto': 'church',

  // -> info-booth (public services/infrastructure)
  information: 'info-booth',
  police: 'info-booth',
  prison: 'info-booth',
  'ranger-station': 'info-booth',
  'fire-station': 'info-booth',
  dentist: 'info-booth',
  veterinary: 'info-booth',
  toilet: 'info-booth',
  'drinking-water': 'info-booth',
  airport: 'info-booth',
  airfield: 'info-booth',
  harbor: 'info-booth',
};
